FROM node:12.13.0-alpine

# where the react app will live
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app
COPY package-lock.json /usr/src/app

RUN npm install

COPY . /usr/src/app

CMD ["npm", "start"]
