version: "3"

services:
  frontend:
    build: ./client
    expose:
      - 4000
    ports:
      - 4000:3000
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
