version: "3"

services:
  server:
    build: ./server
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./server:/usr/src/app
  frontend:
    build: ./client
    expose:
      - 4000
    ports:
      - 4000:3000
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    links:
      - server
